name: Assistant Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  TARGET_DIR: /home/github/test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Update app
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          user: ${{ secrets.USER }}
          command: |
            chmod +x ~/strava_bot/start.sh
            ~/strava_bot/start.sh
      - name: Notificar falha no Telegram
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="O build falhou! Confira os detalhes no GitHub Actions: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d text="${MESSAGE}"